const string BATTERY_MANAGER_DISCHARGE_INTERVAL = "00:00:57"; // HH:MM[:SS]
const string BATTERY_MANAGER_RECHARGE_INTERVAL = "00:00:03"; // HH:MM[:SS]
const uint BATTERY_MANAGER_DRAIN_CHECK_TICKS = 120;
const uint BATTERY_MANAGER_DRAIN_CHECK_THRESHOLD = 100;
